### ISSUE TITLE
error: trigraphs was enabled in PCH file but is currently disabled

### ISSUE THREAD

**Issue by mgerhardy** [sakra/cotire#107]
Can I somehow see where the trigraphs option comes from? I don't use c89 anywhere explicitly.

**Comment by sakra** [comment]
Do a `make VERBOSE=1` in order to see the actual options used upon compilation. Also double check that target properties which affect compilation aren't modified after the `cotire` function has been applied.

**Comment by sakra** [comment]
Fixed in 1.7.9.

**Comment by mbizkit76** [comment]
same error on macOS 10.12.3 Sierra running `make install` command

**Comment by sakra** [comment]
@mbizkit76 @sparsebase Do you have the language standard property (e.g., `C_STANDARD`) set in your project?

**Comment by ProfFan** [comment]
Same problem here installing as a dependency for MRPT. Tried all clues above and no success.

**Comment by Pierre-Sassoulas** [comment]
Under Alpine:edge I have the same error message with cotire 1.7.9, 1.7.10 and the current version. Using "-std=gnu++11" in the compilation options instead of "-std=c++11" or "-std=c++17" fix the problem.
