### ISSUE TITLE
Setting ccache sloppiness in ccache.conf doesn't get detected.

### ISSUE THREAD

**Issue by Zerophase** [sakra/cotire#117]
Having `sloppiness = pch_defines,time_macros` in ccache.conf isn't detected by cotire. 
`fatal error: file 'example_CXX_prefix.hxx' has been modified since the precompiled header
      'example_CXX_prefix.hxx.gch' was built` fires off every time.

**Comment by sakra** [comment]
Fixed in 1.7.10.
