### ISSUE TITLE
Evaluation file to be written multiple times for different configurations or languages with different content

### ISSUE THREAD

**Issue by TaaTT4** [sakra/cotire#120]
As soon as I added a new dependency library to my project, CMake began to raise some errors of this kind during generation: `Evaluation file to be written multiple times for different configurations or languages with different content`

This is my current situation.
I have four CMake projects where everyone of them depends on another one.
To be more specific, Playground (exe) depends on OgreSubstance (dll) which depends on Numen (dll) which finally depends on NumenCrypto (static lib).
Every project is cotired without unity build (`COTIRE_ADD_UNITY_BUILD` is false).

The issue appeared as soon as I added OgreSubstance as a dependency of Playground modifying the dependencies hierarchy chain from this to this:
Playground --> Numen --> NumenCrypto
Playground --> OgreSubstance --> Numen --> NumenCrypto

And the CMake code of Playground from this to this:
```
add_executable(${PROJECT_NAME} WIN32 ${PLAYGROUND_INCLUDES} ${PLAYGROUND_SOURCES} ${PLAYGROUND_RESOURCES} ${PLAYGROUND_CFGS} ${PLAYGROUND_INIS})

target_include_directories(${PROJECT_NAME}
		PUBLIC $<TARGET_PROPERTY:Numen,INCLUDE_DIRECTORIES>
		PUBLIC ../../include/playground
)

target_link_libraries(${PROJECT_NAME}
		Numen
)
```
```
add_executable(${PROJECT_NAME} WIN32 ${PLAYGROUND_INCLUDES} ${PLAYGROUND_SOURCES} ${PLAYGROUND_RESOURCES} ${PLAYGROUND_CFGS} ${PLAYGROUND_INIS})

target_include_directories(${PROJECT_NAME}
		PUBLIC $<TARGET_PROPERTY:OgreSubstance,INCLUDE_DIRECTORIES>
		PUBLIC ../../include/playground
)

target_link_libraries(${PROJECT_NAME}
		OgreSubstance
)
```

The only way to solve I've found so far is to NOT cotire Playground (very frustrating).

Here the CMake configuration log (both `COTIRE_DEBUG` and `COTIRE_VERBOSE` enabled): [https://pastebin.com/ZRHFr5NT](https://pastebin.com/ZRHFr5NT)
Here the CMake generation log: [https://pastebin.com/J3WnYq5e](https://pastebin.com/J3WnYq5e)
Digging the CMake source code, I've found that this error should be raised during `file(GENERATE ...)` command.
See here:
 [https://gitlab.kitware.com/cmake/cmake/commit/9e1689413fd1e54e8056b7d369cd508636987072](https://gitlab.kitware.com/cmake/cmake/commit/9e1689413fd1e54e8056b7d369cd508636987072)

I'm using the latest CMake stable version, 3.8.2 (but I've alrady tried with the latest RC version, 3.9.0-rc3), and I'm generating for Visual Studio 15 2017 Win64.
Since in my scenario this is a KO error, I'm open to make any tests you need.

**Comment by sakra** [comment]
Have you double check that cotire is not invoked more than once for the same target?

**Comment by TaaTT4** [comment]
Yes, I'm pretty sure that cotire is invoked once for every project.

Applying to cotire the patch attached (which prints the target everytime that cotire is invoked), I get the following output:
```
cotire 1.7.9 loaded.
_targets: Numen
_targets: NumenCrypto
_targets: OgreSubstance
_targets: Playground
CXX RC target Playground cotired without unity build.
Configuring done
```
[patch.txt](https://github.com/sakra/cotire/files/1077063/patch.txt)

**Comment by sakra** [comment]
I did not manage to reproduce the problem. Can you set up a small example that reproduces the problem?

**Comment by TaaTT4** [comment]
Here it is (the .h and .cpp files has been overwritten with garbage bytes)!
The CMake configure phase should works without any error, while the generate phase should give you the same issue I have.

Let me know if you need some more tests.

P.S.: I've noticed that the targets on which the error is present vary from run to run.
Could be something related to threads?

[Playground.zip](https://github.com/sakra/cotire/files/1131605/Playground.zip)

**Comment by TaaTT4** [comment]
Hey @sakra, any news on this?
Have you been able to reproduce the issue?

**Comment by TaaTT4** [comment]
I've found that this issue was caused by an improper use of generator expressions on our side.

Apologize me for having bothered you.
I close it.

**Comment by SimonHeybrock** [comment]
@TaaTT4 I have run into the same problem. Would you mind sharing what improper use of generator expressions you are referring to specifically, and how you fixed it?
