### ISSUE TITLE
Errors with CMake 3.9

### ISSUE THREAD

**Issue by ssbanerje** [sakra/cotire#124]
If one adds the following lines in `example/CMakelists.txt` before the `cotire()` call for a CMake 3.9 build generation

```cmake
target_compile_options(example
    PRIVATE
        -W
        $<$<CXX_COMPILER_ID:GNU>:-Wall -Wextra>
        $<$<CXX_COMPILER_ID:Clang>:-Weverything>
        $<$<CXX_COMPILER_ID:AppleClang>:-Weverything>
)
```

The CMake execution fails with the following error message

```
CMake Error at CMake/cotire.cmake:2254 (file):
  Error evaluating generator expression:

    $<CXX_COMPILER_ID:GNU>

  $<CXX_COMPILER_ID> may only be used with binary targets.  It may not be
  used with add_custom_command or add_custom_target.
Call Stack (most recent call first):
  CMake/cotire.cmake:2848 (cotire_generate_target_script)
  CMake/cotire.cmake:3254 (cotire_process_target_language)
  CMake/cotire.cmake:3431 (cotire_target)
  src/CMakeLists.txt:20 (cotire)


CMake Error at CMake/cotire.cmake:2254 (file):
  Error evaluating generator expression:

    $<CXX_COMPILER_ID:GNU>

  $<CXX_COMPILER_ID> may only be used with binary targets.  It may not be
  used with add_custom_command or add_custom_target.
Call Stack (most recent call first):
  CMake/cotire.cmake:2848 (cotire_generate_target_script)
  CMake/cotire.cmake:3254 (cotire_process_target_language)
  CMake/cotire.cmake:3431 (cotire_target)
  src/CMakeLists.txt:20 (cotire)
```

I can confirm that this code compiles with CMake 3.8.x.

**Comment by ssbanerje** [comment]
Even without the compiler check. It seems that `cotire` generates the following error when executing `cmake`

```
Problems were encountered while collecting compiler information:
	<built-in>:1:10: fatal error: '/Users/subho/Workshop/symphony/cmake-build-debug/symphony/cotire/symphony_CXX_prefix.hxx' file not found
```

**Comment by ColinDuquesnoy** [comment]
> Problems were encountered while collecting compiler information:
	<built-in>:1:10: fatal error: '/Users/subho/Workshop/symphony/cmake-build-debug/symphony/cotire/symphony_CXX_prefix.hxx' file not found

Are you using CLion? I am facing the same issue if I run CMake from CLion but not if I use command line.

**Comment by AlexWorx** [comment]
I can confirm: In CLion I have such error messages, which I do not see if I use the command line. 
It did not happen in the past. Unfortunately, I did not work on the project for about 5 months. Now after I updated all software (CLion, CMake, GCC, CLang...) this error shows up on the CLion console. It does not bother me too much, as it does not stop my project from building nicely. 
I consider it a pure CLion thing, so not on cotire side. It might be some other background task they are doing for parsing the project code that causes the error. But this is just a guess.

**Comment by ssbanerje** [comment]
Yes I see the issues in CLion.

**Comment by ColinDuquesnoy** [comment]
The errors disappear if you rerun cmake after you build all_pch. I think it is safe to assume this is a clion indexation parser issue not a cotire one.

@sakra I'd suggest to close this issue

**Comment by FrancescoBorzi** [comment]
Just FYI: I came into this issue by googling, I got exactly the same type of error in another project. Also for me it only happens when running CMake in CLion, not in the command line.

**Comment by Zaffy** [comment]
I opened [an issue](https://youtrack.jetbrains.com/issue/CPP-16409) for CLion, feel free to vote for it to get it fixed sooner.
