### ISSUE TITLE
generated file with wrong include path using clang

### ISSUE THREAD

**Issue by xgdgsc** [sakra/cotire#154]
I' m on latest manjaro using cotire 1.8. A project I cotired generates cxx files with invalid include paths when using clang like the following:
```
#include "/include/c++/7.3.1/vector"
#include "/include/c++/7.3.1/chrono"
#include "/include/c++/7.3.1/unordered_map"
#include "/include/c++/7.3.1/list"
#include "/include/c++/7.3.1/thread"
```
so it doesn' t compile.

The same files work with GCC. And it 's working well with clang on another laptop that' s using the same latest version of manjaro (the toolchain should be the same). Do you have any suggestions on finding the reason for this error? I tried cleaning build directories with no success.

**Comment by sakra** [comment]
Please enable cotire debugging, i.e. (`-D COTIRE_DEBUG=ON`) and paste the resulting output.

**Comment by xgdgsc** [comment]
https://gist.github.com/xgdgsc/0e695b4befd8f67ac93c683dea32c610 Here' s the log. Thanks.

**Comment by sakra** [comment]
The log does not contain the generation of the prefix header (at build time). Do a `make clean` and `make` and gist the resulting log again.

**Comment by sakra** [comment]
Please try the latest version from the `develop` branch.

**Comment by xgdgsc** [comment]
Thanks. This one works well.

There' s one more issue I' m not sure if related to cotire. In the clang build, every time I run build in qtcreator (which calls `"/usr/bin/cmake" --build . --target all`) , with no source code changed, it would scan through all the object files (very fast, seems cached) and rebuild the static libraries. While with gcc, it would do nothing correctly like this:

```
18:52:55: Starting: "/usr/bin/cmake" --build . --target all
ninja: no work to do.
18:52:55: The process "/usr/bin/cmake" exited normally.
```

**Comment by sakra** [comment]
Does the problem go away if disable cotire?

**Comment by xgdgsc** [comment]
Thanks. It seems to be a problem with ccache, not cotire. Adding a Kit of clang works.
