### ISSUE TITLE
Target cannot be cotired

### ISSUE THREAD

**Issue by kreuzerkrieg** [sakra/cotire#178]
The following message appears
> Target XXX cannot be cotired. No ASM or C or CXX source files.

when I add `cotire(XXX)` at the end of my CMakeLists.txt and the XXX clearly has sources
`add_library(XXX ${XXX_headers} ${XXX_sources})`
Any idea where to look for the problem?

**Comment by ZeldaZach** [comment]
Having the same issue on my front. `-- Target XXX cannot be cotired. No C or CXX or RC source files.`

**Comment by hesetone** [comment]
did the issue solved? i have the same issue on my front as @ZeldaZach

**Comment by kreuzerkrieg** [comment]
Modern CMake includes all cotire features like PCH and unity builds
https://cmake.org/cmake/help/latest/command/target_precompile_headers.html
https://cmake.org/cmake/help/latest/variable/CMAKE_UNITY_BUILD.html
