### ISSUE TITLE
Install targets for cotire generated unity builds

### ISSUE THREAD

**Issue by Shootfast** [sakra/cotire#39]
Hi,

I have a large project that builds awesomely quick under cotire, however as all of the `install(TARGETS target)` macros are still pointing to the original targets, the make install step will compile everything again the old slow way.

There doesn't appear to be an install_unity target, so I was just wondering what you thought the best solution to the problem would be.

Cheers,
Mark

**Comment by jcelerier** [comment]
Another possibility that @ngladitz taught me was to remove the dependency on the all target to the install target : 

```
set(CMAKE_SKIP_INSTALL_ALL_DEPENDENCY True)
```

The big advantage is that this allows running cpack easily with the unity targets (else cpack calls `make install` which just rebuilds everything).
