### ISSUE TITLE
Unity builds creating incorrect import library file names on Windows

### ISSUE THREAD

**Issue by peterhuene** [sakra/cotire#46]
With Cotire 1.6.9:

We have a shared library that, for one reason or another, needs to be named with a .so extension, even on Windows (it's a ruby extension).  As such, we set the PREFIX, SUFFIX, IMPORT_PREFIX, and IMPORT_SUFFIX target properties, like so:

```set_target_properties(libfacter PROPERTIES PREFIX "" SUFFIX ".so" IMPORT_PREFIX "" IMPORT_SUFFIX ".so.a" ...)```

When not using unity, this builds `libfacter.so` and `libfacter.so.a` as expected.  When using a unity build for this target, however, we get `libfacter.so` and `liblibfacter.dll.a`.  Cotire seems to be causing it to ignore the import library prefix and suffix properties.

**Comment by sakra** [comment]
Should be fixed in 1.7.0.
