### ISSUE TITLE
  Unknown CMake command "cotire".

### ISSUE THREAD

**Issue by mannanj** [sakra/cotire#48]
hello. I try to make the examples on Ubuntu and encounter the following issue. I have the requirements for Cmake version, GCC installed, not Intel C++ Compiler. I may not understand how GCC/Intel C++ Compiler works, but does this require Intel C++ compiler on top of GCC?

Thanks

**Comment by mannanj** [comment]
The issue is the title of this post, forgot to post it above but here it is again:

I get: 
  Unknown CMake command "cotire".

When i run "cmake" for the examples

**Comment by sakra** [comment]
Please provide a log of your CMake run.

**Comment by mannanj** [comment]
Thank you for the reponse! Are you asking for output from a log file? Or error? If error than this is the error message that shows up:

CMake Error at CMakeLists.txt:10 (include):
  include could not find load file:

    cotire


CMake Error at CMakeLists.txt:38 (cotire):
  Unknown CMake command "cotire".

**Comment by yellowjs0304** [comment]
Hi, I have the same Issue. How Can I solve it??

**Comment by sakra** [comment]
Be sure to run the cmake command on the outermost directory (not the `src` directory).
