### ISSUE TITLE
support large binary objects

### ISSUE THREAD

**Issue by MrMoose** [sakra/cotire#49]
I just learned about cotire and was very impressed. Just what I always wanted! PCH in a box!

So I just tried and applied it to a project on VC11 that is rather heavy on templates boost and spirit and such and it almost worked, until:

 error C3859: virtual memory range for PCH exceeded; please recompile with a command line option of '-Zm378' or greater

I usually have this error in my projects and generally set this option in my own CMake scripts, that are a collection of functions for ease of use and dependency management. 
It would be nice to be able to pass such options into cotire or have them already in place there. 

Cheers,
Moose

**Comment by sakra** [comment]
How many include directives do you have in the prefix header generated by cotire?

**Comment by sakra** [comment]
I have added support for setting the PCH scaling factor in cotire 1.7.0. To configure the scaling factor set the variable `COTIRE_PCH_MEMORY_SCALING_FACTOR` before including cotire:

    set (COTIRE_PCH_MEMORY_SCALING_FACTOR "378")
    include(cotire)

**Comment by MrMoose** [comment]
Wow, that totally slipped my mind. My apologies I didn't respond to your question. Just didn't notice it.

Anyway, I have just included that new option and as it looks like it does build now. I had to crank it up to 500 though but that's OK.

An issue that popped up with this configuration however, is that all of a sudden almost all the objects started throwing thousands of warnings like "decorated name length exceeded, name was truncated". Which are usually not that severe but clutter the build and hide real warnings. Also, I see that the sheer amount of such warnings slows down the compile. It's so many of them, I cannot even use the side bar to scroll. They all seem to come from within boost. 

For example:
"warning C4503: 'boost::proto::exprns_::extends<Expr,Derived>' : decorated name length exceeded, name was truncated"

Also, to my surprise, the speed up seems to exclude some files. Some compile much faster as expected, but others take as long as before or only slightly less. Unfortunately those are the ones with template heavy code that go all the way through boost mpl, proto, phoenix, spirit and such. They generally have compile times of 6 or 7 minutes for one object. They are faster now but still take around 4-5 minutes.

I'm still trying to figure out if it all can work. Unfortunately all my attempts to create a build failed. In some modules, the compiler behaves differently than before.

I get errors with a few cases of templates that are specialized for specific types. The specialization appears to be missing or cannot be found when a typedef'ed symbol is used to deduce. Also, some headers that are aliasing other namespaces all of a sudden fail I guess that's in the nature of PCH though. I will continue to try create a build once I get a chance. Just wanted to give you a quick heads up on that one. Still very promising.

Cheers,
Moose

**Comment by sakra** [comment]
I always add the following flags to disable MSVC's noise warnings:

		# disable noisy "decorated name length exceeded, name was truncated" warning
		set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4503")
		# disable noisy "unreferenced inline function has been removed" warning
		set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4514")
		# disable noisy "function not inlined" warning
		set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4710")
		# disable noisy "padding added after data member" warning
		set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4820")
		# disable noisy "function selected for automatic inline expansion" warning
		set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /wd4711")

The target's first source file is used to precompile the generated header so this one might take longer to compile.

**Comment by paulsapps** [comment]
Hmmm so why would using cotire change the length of a template symbol?
