### ISSUE TITLE
automatic target to unity conversion possible?

### ISSUE THREAD

**Issue by rodion67** [sakra/cotire#55]
I would like to know if it would be possible to simply replace a target a by a unity target, keeping names and everything just not using original cpp files but the unity cpp files for building.
And this should work for any target in a directory. that would make things a lot simpler, at least for me ;-)

Regards,
Gunnar

**Comment by sakra** [comment]
It's not possible to replace an existing CMake target or to change its sources once it is defined. The closest thing to what you want is to make the unity target appear under a different name, i.e.:

    add_executable(example_template main.cpp example.cpp log.cpp log.h example.h)
    set_target_properties(example_template PROPERTIES COTIRE_UNITY_TARGET_NAME "example")
    cotire(example_template)

That way `make example` will perform a unity build.

**Comment by rodion67** [comment]
Ok i see, that was already described in the manual. But couldnt be there a unity_add_library() and unity_add_executable() command, which depending on an option generates unity target or simple cmake targets? SO i could switch easily between these too, installation stuff would also work then.

Regards,
Gunnar

**Comment by mirkow** [comment]
I would also like such functions.
At the moment I cannot make real use of the unity build because some of my targets cannot be built with a unity build.
And for these targets all the other targets need to be build again with the normal target.

**Comment by onqtam** [comment]
@rodion67 @mirkow This is exactly what I have done here: https://github.com/onqtam/ucm/blob/master/ucm.cmake
see the ucm_add_target() macro

documentation is still not available though - coming soon.

**Comment by mirkow** [comment]
great, thanks, I'll try it out

**Comment by mirkow** [comment]
@onqtam looks great so far, but how can I pass additional properties to my target like c++11 cxx compile flags? These need to be forwarded to the pch and unity build and thus cannot be added after your macro.
Is there a way to achieve this already?

**Comment by onqtam** [comment]
@mirkow after my macro the unity target is just like any other target - you may use ```target_compile_definitions``` or any other such per-target stuff.

```
ucm_add_target(NAME game TYPE EXECUTABLE UNITY SOURCES "${sources}")
target_include_directories(game "C:/something")
```

**Comment by mirkow** [comment]
Yeah, but you cannot specify the compile flags beforehand for the target you are creating in your macro but they are required for the PCH.
But the extension of your macro with a compile flag parameter works.

**Comment by onqtam** [comment]
@mirkow arent the pch flags handled by cotire itself?

**Comment by mirkow** [comment]
yes, but CXX_FLAGS need to be specified on the original target before cotire is called
