### ISSUE TITLE
Configure time very slow

### ISSUE THREAD

**Issue by jtotz** [sakra/cotire#58]
If I do not enable cotire for my large-ish project, cmake 3.1.3 takes about 1 minute to configure it.

If I enable cotire (1.6.9) configure time is 45 minutes. Obviously, the compile time improvements I get are totally negated by the excessive configure time.

This seems to be a regression, it didn't used to be like this, i.e. in the past the two configure times were the same.

This is on Windows 7, 8, and 8.1, with cmake 3.1 to 3.1.3 (dont know about newer, cannot check older).

What would be the best way to figure out what is going on?

**Comment by sakra** [comment]
Do you know which older version of cotire was not affected by the problem?

Doing a `cmake -DCOTIRE_DEBUG=On` with your project might give you some clues.

**Comment by jtotz** [comment]
hi sascha,

i tried with COTIRE_DEBUG but i have no idea what to look out for. it just fills the log. i can try a diff of the log of different versions later.

meanwhile:
1.5.1 = fast
1.5.2 = fast
1.6.0 = fast
1.6.3 = fast
1.6.4 = slow
1.6.6 = slow
1.6.9 = slow

**Comment by sakra** [comment]
One way to reduce the configure time is to apply cotire only to a subset of the project configurations, e.g.

    cotire(mytarget CONFIGURATIONS Debug Release)

**Comment by jtotz** [comment]
We only ever build/configure a single project config, either debug or release (but i just realise that cmake might still generate lots of unnecessary stuff, depending on CMAKE_CONFIGURATION_TYPES).

I tried explicitly setting the CONFIGURATIONS options. It does improve time a bit, but nowhere near the 1 minute mark of earlier versions.

**Comment by jtotz** [comment]
Forgot to mention this ealier: this is with Visual Studio 2012 64-bit generator.

**Comment by sakra** [comment]
I have just pushed version 1.7.2 of cotire, where I have rolled backed some of the changes introduced in 1.6.4 - 1.6.9. Please give this new version a try.

**Comment by jtotz** [comment]
1.7.2 fixed it! configure time is down to 1 minute (with cmake 3.2.2, on windows, vs2012, x64).

**Comment by jtotz** [comment]
thanks for looking into it!
