### ISSUE TITLE
Problems with unity build in VS and solution explorer

### ISSUE THREAD

**Issue by onqtam** [sakra/cotire#60]
So I cotire'd a project with ~140 source files and was cleaning compilation errors and suddenly after some re-run of cmake I no longer could open the generated unity .cxx files from the solution explorer.

This is what the Output window says when they are generated:

```
Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_0_17.cxx
1>  Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_18_35.cxx
1>  Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_36_53.cxx
1>  Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_54_71.cxx
1>  Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_72_89.cxx
1>  Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_90_107.cxx
1>  Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_108_125.cxx
1>  Generating CXX unity source vray4maya/Release/cotire/vrayformaya_ORIGINAL_CXX_unity_126_138.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_0_17.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_18_35.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_36_53.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_54_71.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_72_89.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_90_107.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_108_125.cxx
1>  vrayformaya_ORIGINAL_CXX_unity_126_138.cxx
```

And indeed these files are created on the filesystem and are getting compiled, but when I navigate to them in the solution explorer and double click on a .cxx file to play with it I get this error:

```
Could not find a part of the path
'C:\cmake_msvc\vray4maya\Debug\cotire\vrayformaya_ORIGINAL_CXX_unity_0_17.cxx`.
```

But I am currently on the Release configuration! And everything actually compiles! 

In the root CMakeLists.txt file I remove all configurations except for "Release" like this:

```
cmake_minimum_required(VERSION 3.0.0)
# For now disable all configurations except for Release
set(CMAKE_CONFIGURATION_TYPES Release CACHE TYPE INTERNAL FORCE )
include("${CMAKE_CURRENT_SOURCE_DIR}/build_scripts/cmake/macros/cotire.cmake")
```

Here is a screenshot of the error:

![untitled](https://cloud.githubusercontent.com/assets/4648169/7278217/a869e04e-e91c-11e4-89d0-f7caa3f93988.png)

And the weird part is that initially I had no such problem. When I got this though I deleted everything from the out-of-source dir, restarted the computer and re-ran everything and I still could not open the generated .cxx files from the solution explorer.

Any ideas?

**Comment by onqtam** [comment]
After removing the unity target and then adding it again in the project a few times it started working again... There is something fishy here.

**Comment by sakra** [comment]
Cotire generated files a configuration specific. Switching your configuration (i.e., Debug, Release) in the Visual Studio IDE may result in the files not being found by the IDE.

**Comment by onqtam** [comment]
But there is only one configuration - Release. Today it doesn't work again. I will try to narrow down when this happens.

**Comment by onqtam** [comment]
I cannot reproduce this problem at home, and at work after I generate the unity source files, close VS and reopen it, then I can click on the files and they open properly. So with reopening VS there is no problem...

I will close this issue - I have no idea why it happens but it isn't a major problem.
