### ISSUE TITLE
Appending to `CMAKE_MODULE_PATH` results in unwanted macro definition

### ISSUE THREAD

**Issue by procedural** [sakra/cotire#63]
Hi, @sakra! We have this issue in OF project with Cotire:

https://github.com/ofnode/of/issues/12

Cotire defines a macro which triggers compile time error in GLEW.

Can you look at this? Thanks!

Tested with Cotire 1.7.2.

**Comment by sakra** [comment]
Looking at the issue, it seems that this is problem intrinsic to using a precompiled header. The prefix header includes system headers in one particular order which may not be suitable for all compilation units. See the cotire manual section on the property `COTIRE_PREFIX_HEADER_INCLUDE_PRIORITY_PATH` for a possible work-around.

**Comment by procedural** [comment]
Thanks, Sascha! Good to know that it is a known issue. I will look at the documentation and reopen the issue if something go wrong aside from that case we had yesterday.
