### ISSUE TITLE
Doesn't use "-pthread" on building precompiled header, if in add_definitions()

### ISSUE THREAD

**Issue by darlingm** [sakra/cotire#64]
cmake states "cotire 1.7.2 loaded", and "CXX target myLibrary cotired."

"Building CXX precompiled header myLibrary/cotire/myLibrary_CXX_prefix.hxx.pch" shows clang is not being given "-pthread" as a compilation option.  myLibrary's CMakeLists.txt includes "add_definitions(-DXYZ -pthread)".  But, clang is being given "-DXYZ" as a compilation option.  So, I think cotire is maybe only passing along add_definitions that start with -D, or something along those lines.

Building CXX object myLibrary/CMakeFiles/myLibrary.dir/myLibrary.cpp.o" shows clang is being given "-pthread" as a compilation option.

This causes clang to give:

error: POSIX thread support was disabled in PCH file but is currently enabled

Using gcc, it does the same, except with this error:

error: .../cotire/...hxx.gch: not used because `_REENTRANT' is defined [-Werror=invalid-pch]

Running cotire from git (1.7.2), cmake 3.2.20150515-g2e4ea, clang (3.7.0-pre, git trunk 236925), gcc (6.0.0-pre, 5/17/2015).

I got around the problem by moving "-pthread" from add_definitions() to set(CMAKE_CXX_FLAGS_DEBUG...)

Happy to do that, and it makes more sense there.  But, the cmake documentation says you can specify switches with add_definitions() rather than CMAKE_CXX_FLAGS_*

**Comment by sakra** [comment]
Starting with CMake 2.8.12 it is recommended to use `add_compile_options` instead of `add_definitions` to add compile options, i.e.:

    add_compile_options(-pthread)

**Comment by victormwenda** [comment]
All you need to do is link with pthread

`target_link_libraries(BUILD_ARTIFACT pthread)`

BUILD_ARTIFACT can be your project, or library name

P.S Add this line after defining your ARTIFACT
