### ISSUE TITLE
Using CXX_STANDARD property on target doesn't affect the PCH compilation

### ISSUE THREAD

**Issue by tru** [sakra/cotire#66]
Instead of doing `set(CMAKE_CXX_FLAGS ${CMAKE_CXX_FLAGS} -std=gnu+11)` the preferred way is to use `set_target_property(target CXX_STANDARD 11)` to indicate what flags should be used. The problem is that cotire doesn't seem to detect that and compiles the PCH without the C++11 flags which leads to the following error: `error: C++11 was disabled in PCH file but is currently enabled`

**Comment by sakra** [comment]
The target properties `CXX_STANDARD` and `CXX_EXTENSIONS` will be handled correctly in a future version.

**Comment by sakra** [comment]
Just pushed version 1.7.3 which handles `CXX_STANDARD` and `CXX_EXTENSIONS`.
