### ISSUE TITLE
problems with number of sources in unity build files

### ISSUE THREAD

**Issue by onqtam** [sakra/cotire#67]
In MANUAL.md ```COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES``` is referenced only regarding precompiled headers. But when changing it from 3 (the default) to 2 (and passing it from the command line to cmake) I get unity source files like these:

```
Game_ORIGINAL_CXX_unity_0_1.cxx
Game_ORIGINAL_CXX_unity_2_3.cxx
```

I had previously used ```COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES``` and the target property ```COTIRE_UNITY_SOURCE_MAXIMUM_NUMBER_OF_INCLUDES``` and they indeed work for managing these things about the unity build, but the other one that is mentioned only for precompiled headers shouldn't have to do anything with the unity sources.

Currently I am not mixing the usage of

```
COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES
```
```
COTIRE_MAXIMUM_NUMBER_OF_UNITY_INCLUDES
```
and 
```
COTIRE_UNITY_SOURCE_MAXIMUM_NUMBER_OF_INCLUDES
```

**Comment by sakra** [comment]
Just pushed version 1.7.3 which removes the effect of `COTIRE_MINIMUM_NUMBER_OF_TARGET_SOURCES` on the generated unity target.

**Comment by onqtam** [comment]
Now unity source files get created with only one source file included in them by default:

```C++
// game_ORIGINAL_CXX_unity_0_0.cxx
#ifdef __cplusplus
#include "D:\game\libs\third_party\ucm\examples\a.cc"
#endif
```
```C++
// game_ORIGINAL_CXX_unity_1_1.cxx
#ifdef __cplusplus
#include "D:\game\libs\third_party\ucm\examples\b.cc"
#endif
```

Maybe it should default to something else but this is not a problem IMHO because the ```COTIRE_UNITY_SOURCE_MAXIMUM_NUMBER_OF_INCLUDES``` target property works.
