### ISSUE TITLE
unity target fails to build with custom prefix header

### ISSUE THREAD

**Issue by onqtam** [sakra/cotire#68]
The unity target for the game executable fails to build but the original target succeeds (cotire 1.7.2):

```cmake
#CMakeLists.txt
cmake_minimum_required(VERSION 2.8.12)
include(cotire.cmake)
add_executable(game a.cc b.cc c.cc pch.h)
set_target_properties(game PROPERTIES COTIRE_CXX_PREFIX_HEADER_INIT "pch.h")
cotire(game)
```

```C++
//pch.h
#pragma once
#include <vector>
```

```C++
//a.cc
int main() { return 5; }
```

```C++
//b.cc
void b() { std::vector<int> b; }
```

```C++
//c.cc
void c() { std::vector<int> c; }
```

The thing is that while I only used a prefix header and not a unity build I got used to having the pch as a prefix header (since that's what cotire does with it) and I didn't ```#include``` it anywhere. Now I want to use a unity build but the header is not prefix-ed to any of the generated ```.cxx``` unity sources (and inspecting the options in the IDE they don't seem to be using a pch at all).

**EDIT:**
After including the pch everywhere everything built successfully as the unity target, but I found no precompiled header from my prefix one. When building the original target though I am able to find the 10-20 MB binary for that pch in the build dir. This is a bug.

**Comment by sakra** [comment]
Will be fixed in a future version.

**Comment by onqtam** [comment]
In 1.7.3 this case is fixed, but if there are excluded sources from the unity build - they don't get the header prefixed - only the unity source files get it (and if there was no unity build at all and just a pch they would have).

**Comment by onqtam** [comment]
made into a separate issue
