### ISSUE TITLE
Problem with QtWidgets on OS X

### ISSUE THREAD

**Issue by jcelerier** [sakra/cotire#69]
Hello,

I use cotire for a Qt project.

I have some "generic" Qt includes like this one :

`#include <QtWidgets>`

And in the `project_CXX_prefix.cxx`, I get :

`#include "/Users/jcelerier/Qt/5.4/clang_64/lib/QtWidgets.framework/QtWidgets"` which is not the header file (which is located in the `QtWidgets.framework/Headers`folder), but a symlink to the dylib! This of course does not build.

The same project builds just fine with cotire under Linux, with both GCC and Clang.

**Comment by sakra** [comment]
Can you please run cotire with the option `COTIRE_DEBUG` turned on, i.e.: 

    cmake -DCOTIRE_DEBUG=TRUE .

Then copy the resulting output to this thread as a comment.

**Comment by jcelerier** [comment]
Seems like updating Qt fixed it.
