### ISSUE TITLE
Generating PCH with Clang conflicts with -save-temps compiler flag

### ISSUE THREAD

**Issue by j3lamp** [sakra/cotire#70]
Adding `-save-temps` to `CMAKE_CXX_FLAGS` causes clang to produce the following error when generating a PCH:

```
error: invalid value 'c++-header-cpp-output' in '-x c++-header-cpp-output'
```

I was able to fix this by modifying the function `cotire_precompile_prefix_header` to call

``` cmake
list(REMOVE_ITEM _option_COMPILE_FLAGS "-save-temps")
```

before it calls

``` cmake
cotire_add_compile_flags_to_cmd(_cmd ${_option_COMPILE_FLAGS})
```

This feels like a hack to me … there is probably a more correct way to handle this in cotire, but I'm not sure where/how.

_Note:_ This seems to, at least in some cases, affect GCC as well but it just produces strange errors, e.g. 

```
error: ‘__FILE__’ was not declared in this scope
```

---

I saw this error with cotire 1.6.1 on OS X/clang and was able to repeat it with cotire 1.7.2. I only tested my "fix" with version 1.6.1 on OS X/clang.

On OS X I was using

```
> cmake --version
cmake version 2.8.12.2
> clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin12.6.0
Thread model: posix
```

On Linux I was using

```
> cmake --version
cmake version 2.8.12.2
> gcc --version
gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-7)
```

**Comment by sakra** [comment]
The flag `-save-temps` appears to be incompatible with precompiled header compilation.

Note that CMake generated makefiles contain rules for both the generation of a preprocessed source and the assembly source code. E.g. for the cotire example project:

    $ cd src
    $ make example.cpp.s
    Compiling CXX source to assembly CMakeFiles/example.dir/example.cpp.s
    $ make example.cpp.i
    Preprocessing CXX source to CMakeFiles/example.dir/example.cpp.i

So there is probably no need to add the  `-save-temps` option manually.
