### ISSUE TITLE
New cotire ignores add_definitions(-mXXX)

### ISSUE THREAD

**Issue by danilaml** [sakra/cotire#73]
Cotire 1.6.1: https://travis-ci.org/danilaml/rpcs3/jobs/75754798
`
-- execute_process: /usr/bin/clang++-3.6;-DwxGUI;-DGL_GLEXT_PROTOTYPES;-DGLX_GLXEXT_PROTOTYPES;-D_FILE_OFFSET_BITS=64;-DWXUSINGDLL;-D__WXGTK__;-D__STDC_LIMIT_MACROS;-D__STDC_CONSTANT_MACROS;-DLLVM_AVAILABLE;-DNDEBUG;-D_NDEBUG;-std=c++14;-fexceptions;-pthread;-L/home/travis/build/danilaml/rpcs3/build/rpcs3/../asmjit/;-O3;-O1;-msse;-msse2;-mcx16;-mssse3;-I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0-unofficial;-I/usr/include/wx-3.0-unofficial;-I/usr/include/AL;-I/usr/lib/llvm-3.6/include;-I/home/travis/build/danilaml/rpcs3/rpcs3/../ffmpeg/linux/x86_64/include;-I/home/travis/build/danilaml/rpcs3/rpcs3;-I/home/travis/build/danilaml/rpcs3/rpcs3/Loader;-I/home/travis/build/danilaml/rpcs3/rpcs3/Crypto;-I/home/travis/build/danilaml/rpcs3/rpcs3/..;-I/home/travis/build/danilaml/rpcs3/rpcs3/../asmjit/src/asmjit;-w;-x;c++-header;-c;/home/travis/build/danilaml/rpcs3/build/rpcs3/cotire/rpcs3_CXX_prefix.hxx;-o;/home/travis/build/danilaml/rpcs3/build/rpcs3/cotire/rpcs3_CXX_prefix.hxx.pch
`
1.7.3: https://travis-ci.org/danilaml/rpcs3/jobs/75757637
`
-- execute_process: /usr/bin/clang++-3.6;-DwxGUI;-DGL_GLEXT_PROTOTYPES;-DGLX_GLXEXT_PROTOTYPES;-D_FILE_OFFSET_BITS=64;-DWXUSINGDLL;-D__WXGTK__;-D__STDC_LIMIT_MACROS;-D__STDC_CONSTANT_MACROS;-DLLVM_AVAILABLE;-DNDEBUG;-D_NDEBUG;-std=c++14;-fexceptions;-pthread;-L/home/travis/build/danilaml/rpcs3/build/rpcs3/../asmjit/;-O3;-O1;-I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0-unofficial;-I/usr/include/wx-3.0-unofficial;-I/usr/include/AL;-I/usr/lib/llvm-3.6/include;-I/home/travis/build/danilaml/rpcs3/rpcs3/../ffmpeg/linux/x86_64/include;-I/home/travis/build/danilaml/rpcs3/rpcs3;-I/home/travis/build/danilaml/rpcs3/rpcs3/Loader;-I/home/travis/build/danilaml/rpcs3/rpcs3/Crypto;-I/home/travis/build/danilaml/rpcs3/rpcs3/..;-I/home/travis/build/danilaml/rpcs3/rpcs3/../asmjit/src/asmjit;-x;c++-header;-c;/home/travis/build/danilaml/rpcs3/build/rpcs3/cotire/rpcs3_CXX_prefix.hxx;-o;/home/travis/build/danilaml/rpcs3/build/rpcs3/cotire/rpcs3_CXX_prefix.hxx.pch
`

We have this code in CmakeLists:

```cmake
if (NOT MSVC)
	add_definitions(-DwxGUI)
	set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14 -fexceptions")
	set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g -D_DEBUG")
	set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_CXX_FLAGS_MINSIZEREL} -Os -D_NDEBUG")
	set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O1 -D_NDEBUG")
	set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELWITHDEBINFO} -O1 -g -D_NDEBUG")
	set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} -g -D_DEBUG")
	set(CMAKE_C_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} -Os -D_NDEBUG")
	set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} -O1 -D_NDEBUG")
	set(CMAKE_C_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} -O1 -g -D_NDEBUG")
	add_definitions(-msse -msse2 -mcx16 -mssse3)
...
```
-msse -msse2 -mcx16 -mssse3 is missing from 1.7.3
Also it complains about unused -L asmjit for some reason with newer cotire (but I'm not sure this is wrong)

**Comment by sakra** [comment]
Use `add_compile_options` instead of  `add_definitions` to add compile flags.

**Comment by danilaml** [comment]
But is it intended behaviour? In cmake doc it says `This command can be used to add any flags, but it is intended to add preprocessor definitions.`  So it's not encouraged but possible (and I've seen some projects use it. For example for -Wall and such). And it worked in older cotire. Couldn't find anything about this in changelogs.

**Comment by sakra** [comment]
It is a side effect of requiring CMake 2.8.12 as a minimal version. Compile flags added with `add_definitions ` were exposed through the deprecated directory property `DEFINITIONS` which has been completed removed in CMake 3+.

**Comment by danilaml** [comment]
@sakra ok, thanks for helping out.
