### ISSUE TITLE
Maintain include filer ordering (required for GLEW)

### ISSUE THREAD

**Issue by kolis** [sakra/cotire#74]
I'm working on a project that use GLEW for handling OpenGL features/dependencies. I get errors when building, the include files seem to be reordered, which is a problem for GLEW.

```
error: gl.h included before glew.h
```

And if I check the generated .cxx-file I see that the order is wrong.

**Comment by onqtam** [comment]
```c++
//a.cpp
#include <gl.h>
```

```c++
//b.cpp
#include <glew.h>
```

```c++
// unity .cxx file generated by cotire
#include "a.cpp"
#include "b.cpp"
```

If this is the situation then you should add ```a.cpp``` and ```b.cpp``` in a different order in the original cmake target.

```add_executable(game b.cpp a.cpp)
```

**Comment by kolis** [comment]
Yes, this resolves it. Tnx!
