### ISSUE TITLE
CMAKE_OSX_SYSROOT with an SDK name is not handled properly

### ISSUE THREAD

**Issue by teki** [sakra/cotire#75]
"${CMAKE_${_language}_SYSROOT_FLAG}" "${CMAKE_OSX_SYSROOT}" will break when CMAKE_OSX_SYSROOT is not a path.
CMAKE_OSX_SYSROOT was originally meant to be used with the --sysroot option of the compiler, which accepts sdk names (like macosx10.9) and paths too.

CMake handles this by replacing the value of CMAKE_OSX_SYSROOT with the path for non Xcode generators, see the end of CMake/Modules/Platform/Darwin-Initialize.cmake:

```
if(NOT "${CMAKE_GENERATOR}" MATCHES "Xcode")
    set(CMAKE_OSX_SYSROOT "${_CMAKE_OSX_SYSROOT_PATH}")
endif()
```

**Comment by sakra** [comment]
Since `Darwin-Initialize.cmake` corrects the value for `CMAKE_OSX_SYSROOT` if necessary, cotire should pick up the corrected value. This is probably only an issue if the variable is explicitly set in a CMake list file. Correct?
