### ISSUE TITLE
Cotire does not honor CMAKE_lang_VISIBILITY_PRESET and CMAKE_VISIBILITY_INLINES_HIDDEN variables

### ISSUE THREAD

**Issue by zapolnov** [sakra/cotire#78]
When using one of this option, precompiled header is compiled without them which results into the following error on OSX:
```
error: value symbol visibility differs in PCH file vs. current file
```

Steps to reproduce:
1) Download test project from https://github.com/zapolnov/cotire_bug_report
2) Invoke cmake
3) Invoke make

**Comment by sakra** [comment]
Fixed in cotire 1.7.5. Thanks for providing the handy project to reproduce the bug.
