### ISSUE TITLE
using qt_wrap_cpp, moc’ing of any file causes PCH regeneration

### ISSUE THREAD

**Issue by Optiligence** [sakra/cotire#79]
maybe there is a way to narrow [this](https://github.com/sakra/cotire/blob/cotire-1.7.5/CMake/cotire.cmake#L2050) down a bit

**Comment by sakra** [comment]
Try setting the `COTIRE_EXCLUDED` on the files being moc'ed.

**Comment by Optiligence** [comment]
I commented the linked line in `cotire.cmake` to prevent this, setting `COTIRE_EXCLUDED` doesn’t help. 
As the reason this is happening already is a workaround, i’d like to avoid a workaround for side effects of a workaround though.

**Comment by sakra** [comment]
Which compiler do you use?

**Comment by Optiligence** [comment]
gcc and clang

**Comment by sakra** [comment]
I have added a fix for the issue in cotire 1.7.6.

**Comment by Optiligence** [comment]
Thank you very much.
