### ISSUE TITLE
Policy CMP0058 problem with ninja build system (Cmake 3.0)

### ISSUE THREAD

**Issue by gerstrong** [sakra/cotire#81]
I though putting this here. I think some line is just missing:

cotire 1.7.6 loaded.
Preparing the Build-System for Commander Genius
Setting SYSTEM_DATA_DIR to /usr/share/games
Using shared SDL Version 2 for Commander Genius
WARNING: You did not specify the build type with the -DBUILD_TARGET= Parameter. LINUX has been choosen
Available builds are: WIN32, LINUX GP2X. WIZ, CAANOO, DINGOO, NANONOTE
Boost version: 1.60.0
Using shared SDL Version 2 for Commander Genius
DOSBox-Fusion: OFF
Refkeen for Keen Dreams: ON
CPACK_PACKAGE_VERSION = 1.9.1-Beta
Build system is prepared. To Build the project just type "make"
If you want to create the installation package just type "make package" after you build the project
Configuring done
Generating done
CMake Warning (dev):
  Policy CMP0058 is not set: Ninja requires custom command byproducts to be
  explicit.  Run "cmake --help-policy CMP0058" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  This project specifies custom command DEPENDS on files in the build tree
  that are not specified as the OUTPUT or BYPRODUCTS of any
  add_custom_command or add_custom_target:

   src/CGeniusExe_CXX_cotire.cmake

  For compatibility with versions of CMake that did not have the BYPRODUCTS
  option, CMake is generating phony rules for such files to convince 'ninja'
  to build.

  Project authors should add the missing BYPRODUCTS or OUTPUT options to the
  custom commands that produce these files.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by sakra** [comment]
To fix the warning, set the policy in your project:

    if(POLICY CMP0058) 
        cmake_policy(SET CMP0058 NEW) 
    endif() 

Also see http://cmake.3232098.n2.nabble.com/Seemingly-unfixable-warning-about-CMP0058-after-upgrade-to-CMake-3-3-td7591643.html

**Comment by gerstrong** [comment]
Awesome, works for me, thanks!

**Comment by aktzbn** [comment]
Setting of policy did not work for me. Cmake version is 3.14.19050301-MSVC_2. 

Could you please help me to understand how setting of `cmake_policy(SET CMP0058 NEW)` helps in explicit specification of _*cotire.cmake_ files as byproducts?
