### ISSUE TITLE
Redefinition Header Files (winsock2.h)

### ISSUE THREAD

**Issue by Liryna** [sakra/cotire#93]
Hi,

I face redefinition error at build time with winsock2 header content while using cotire. On Windows the header `<winsock2.h>` is very sensitive at include order with `<windows.h>`.

Does anyone have already faced the issue ?
Is there any possibility with cotire to protect such behaviour of redinition ?

Information: http://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h
Project used with cotire: https://github.com/islog/liblogicalaccess

If you need any further informations, feel free to ask :smiley:

**Comment by gjasny** [comment]
Just define ``WIN32_LEAN_AND_MEAN`` project wide. Contrary to the reading things get better :)

**Comment by Liryna** [comment]
Thank you @gjasny I just added `WIN32_LEAN_AND_MEAN` in the global definitions as you said and it worked :smiley: !
