### ISSUE TITLE
Windows-style path separator in include dirs cause parsing failure

### ISSUE THREAD

**Issue by wdx04** [sakra/cotire#95]
In some cases CMake will not automatically replace '\' with '/' in incude directories, for example, when an include directory is added by the INTERFACE_INCLUDE_DIRECTORIES property. When there are '\'s in include directories, cotire will fail to parse the string by treating '\' as an escaping character.
My solution is replacing '\' with '/' before parsing:

```
    if (CMAKE_${_language}_IMPLICIT_INCLUDE_DIRECTORIES)
        list (REMOVE_ITEM _includeDirs ${CMAKE_${_language}_IMPLICIT_INCLUDE_DIRECTORIES})
    endif()
+   if (WIN32)
+       string (REPLACE "\\" "/" _includeDirs "${_includeDirs}")
+   endif()
    if (COTIRE_DEBUG AND _includeDirs)
        message (STATUS "Target ${_target} include dirs: ${_includeDirs}")
    endif()
```

**Comment by sakra** [comment]
Fixed in 1.7.9.
