### ISSUE TITLE
set(CMAKE_CXX_EXTENSIONS OFF) is not applied to PCH

### ISSUE THREAD

**Issue by Optiligence** [sakra/cotire#99]
`*_CXX_cotire.cmake` still contain `-std=gnu++14` in contrast to the targets which use `-std=c++14`
Compilers throw different warnings/errors about macros or feature disparity in the PCH. 
https://cmake.org/cmake/help/v3.5/prop_tgt/CXX_EXTENSIONS.html

**Comment by sakra** [comment]
Fixed in 1.7.9.
